sitefucidi/Matricula/urls.py
from django.urls import path

from .views import MatriculasList, CAdmisionListaEstudiante, cMatricula, MatriculaFicha, pdfMatricula_view, \
    cMatriculaEditar

urlpatterns = [
    path('matriculas/', MatriculasList.as_view(), name='MatriculasList'),
    path('matriculas/adm/est/', CAdmisionListaEstudiante, name='ListAdm'),
    path('matricula/estudiante/(?P<id_adm>\d+)/$', cMatricula, name="Matricula"),
    path('matricula/estudiante/ficha/(?P<pk>\d+)/$', MatriculaFicha.as_view(), name="MatriculaFicha"),
    path('matriculas/editar/estudiante/(?P<id_mat>\d+)/$', cMatriculaEditar, name="EditarMatricula"),

    # Reportes URLS

    path('matricula/pdf/(?P<pk>\d+)/', pdfMatricula_view.as_view(), name='ReporteMatricula'),
]

sitefucidi/Pago/urls.py
from django.urls import path

from .views import PagosMatriculaList, cAgregarValor, pdfPagoMatricula_view, PagosColegiaturaList, \
    PagosColegiaturaEstudHabilList, cAgregarPago, cFichaPago, pdfEstadoPagoMatricula_view, pdfEstadoPagoMatricula_view1, \
    pdfPagoColegiatura_view

urlpatterns = [
    path('lista/', PagosMatriculaList.as_view(), name='PagoLista'),
    path('detalle/pagos/(?P<id_pago>\d+)/$', cAgregarValor, name='PagoDetalle'),

    path('pago/matricula/pdf/(?P<pk>\d+)/', pdfPagoMatricula_view.as_view(), name='ReportePagoMatricula'),

    path('reportes/(?P<pk>\d+)/', pdfEstadoPagoMatricula_view.as_view(), name='ReporteGeneralPago'),

    path('pago/matricula/pdf/reporte/pago1/', pdfEstadoPagoMatricula_view1.as_view(), name='ReporteGeneralPago1'),
    #creacion de urls para pagos de colegiatura

    path('lista_pc/', PagosColegiaturaList.as_view(), name='PagoListaColegiatura'),
    path('lista_est_pc/', PagosColegiaturaEstudHabilList.as_view(), name='PagoEstudianteHabColegiatura'),
    path('agregar/pago/(?P<id_pago>\d+)/$', cAgregarPago, name='PagoColegiatura'),
    path('ficha/pago/(?P<id_pago>\d+)/$', cFichaPago, name='FichaPagoColegiatura'),
    path('pago/colegiatura/pdf/(?P<pk>\d+)/', pdfPagoColegiatura_view.as_view(), name='ReportePagoColegiatura'),




]

sitefucidi/sitefucidi/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', admin.site.urls,name='login'),
    path('', LoginView.as_view(template_name='usuarios/index.html'), name="Menu"),
    path('salir/', LogoutView.as_view(template_name='usuarios/index.html'), name="logout"),
    path('Menu', include('administrador.urls')),
    path('profile/', include(('administrador.urls', 'prof'), namespace='prof'),name='prof'),
    path('academia/', include(('Academico.urls', 'academia'), namespace='academia'),name='academia'),
    path('admision/', include(('Admision.urls', 'admision'), namespace='admision'),name='admision'),# incluimos las urls de admision para generar el sistema
    path('matricula/', include(('Matricula.urls', 'matricula'), namespace='matricula'), name='matricula'), # incluimos las urls de admision para generar el sistema
    path('pagos/', include(('Pago.urls', 'pago'), namespace='pago'), name='pago'), # incluimos las urls de admision para generar el sistema

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitefucidi/Academico/models.py
from django.db import models


# Create your models here.

class Programa(models.Model):
    opciones = (
        ('N', 'No definido'),
        ('A', 'Anual'),
        ('M', 'Mensual'),
    )

    cod_programa = models.CharField(max_length=10, null=False, verbose_name="Codigo Prograna", unique=True)
    nombre_programa = models.CharField(max_length=70, null=False, verbose_name="Programa")
    duracion = models.IntegerField(verbose_name="Duracion")
    tipo_programa = models.CharField(max_length=10, default=None, choices=opciones, verbose_name="Modalidad Programa")
    # precio_matricula = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor Matricula",default=None)
    # precio_pension = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor Pension",default=None)
    vigencia = models.BooleanField()

    def __str__(self):
        return '{}'.format(self.nombre_programa)


class Valor_matricula(models.Model):
    fecha = models.DateField(
        verbose_name="Fecha Asignada")  # solo se Permite una Fecha unica para los valores no se puede repetir en la tabal
    valor_matricula_presencial = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Matricula ",
                                                     default=None)
    valor_matricula_online = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor Matricula",
                                                 default=None)
    cod_programa = models.ForeignKey('Programa', on_delete=models.CASCADE, verbose_name="Codigo Prograna")
    # 001 12/04/2021  25.00 15.00 PA  order_by (desc).top(1)
    # 002 15/04/2021  25.00 10.00 PA


class Materia(models.Model):
    opcionesM = (
        ('C', 'Creditos'),
        ('H', 'Horas'),
    )
    nivels = (
        (1, 'Uno'),
        (2, 'Dos'),
        (3, 'Tres'),
    )
    materia_id = models.IntegerField(null=False)
    cod_programa = models.ForeignKey('Programa', on_delete=models.CASCADE, verbose_name="Codigo Prograna")
    cod_materia = models.CharField(max_length=10, verbose_name="Codigo Asignatura", primary_key=True)
    nombre_materia = models.CharField(max_length=70, null=False, verbose_name="Asignatura")
    modalidad = models.CharField(max_length=10, choices=opcionesM)
    duracion = models.IntegerField(null=False)
    nivel = models.IntegerField(null=True, blank=True, choices=nivels, default=0)
    valor_presencial = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Presencial ")
    valor_online = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Online")
    estado = models.BooleanField()

    def __unicode__(self):
        return self.Programa.cod_programa

    def __str__(self):
        return '{}'.format(self.nombre_materia)


class CnotasEstudiante(models.Model):
    fecha_subir_nota = models.DateField(verbose_name="Fecha Nota")
    notaestudiante = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Nota")
    asitencia = models.IntegerField()
    id_pago_materia = models.ForeignKey('Pago.Pago', on_delete=models.CASCADE, verbose_name="Id_materia_recibir")
    # id del pago que se genero con esa orden de pago

sitefucidi/Matricula/models.py
from django.db import models

# Create your models here.
class Matricula(models.Model):
    opciones = (
        ('Presencial', 'Presencial'),
        ('Online', 'Online'),
    )
    id_matricula = models.IntegerField(null=False) # sirve para generar el codigo de matricula
    cod_matricula = models.CharField(primary_key=True,verbose_name="Codigo Matricula",max_length=10,default=None)
    admision_id = models.ForeignKey('Admision.admisione', on_delete=models.CASCADE, verbose_name="Admisione")
    fecha_matricula = models.DateField(null=False,default=None)
    modalidad = models.CharField(max_length=15,choices=opciones,default=None)
    porcentaje_beca = models.IntegerField(null=False, default= 0) # para indicar el Porcentaje de descauento por beca
    extesion = models.CharField(max_length=50,default=None)
    valor_pagar = models.DecimalField(max_digits=6, decimal_places=2, default=0, verbose_name="Valor a pagar")

    def __str__(self):
        return self.cod_matricula

sitefucidi/Matricula/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.staticfiles import finders
from django.db.models import Max
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.dateparse import parse_date
from django.utils.functional import empty
from django.views import View
from xhtml2pdf import pisa

from .forms import cMatriculaForm
from .models import Matricula
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from Admision.models import admisione
from Academico.models import Valor_matricula

import os
from django.conf import settings

from Pago.models import Pago


class MatriculasList(LoginRequiredMixin, ListView):
    model = Matricula
    template_name = 'matriculas/matriculas.html'

    def get_context_data(self, **kwargs):
        matriculas = Matricula.objects.all()
        context = super(MatriculasList, self).get_context_data(**kwargs)
        context['matriculas'] = matriculas
        context['Titulo'] = "Matrículas"
        return context


def CAdmisionListaEstudiante(request):
    adm = admisione.objects.all()  # obtengo las admisiones de un estudiante...
    ac = 0  # contador para ver estudiantes con matricula
    ne = 0  # contador para ver estudiantes sin matriucla
    contexto = {'pvigentes': ac, 'nvigentes': ne, 'Titulo': 'Estudiantes para Matricula', 'admisiones': adm}
    return render(request, 'matriculas/generarMatricula.html', contexto)


def cMatricula(request, id_adm):
    adm = admisione.objects.get(id=id_adm)  # Datos de la Admision a Generar Matricula
    # materias = Materia.objects.all().filter(cod_programa=adm.Programa.id)
    valores_pagar = Valor_matricula.objects.all().filter(cod_programa=adm.Programa.id).order_by('-id')[:1]
    materiasMatriculdas = Matricula.objects.all().filter(admision_id=adm.id)
    valor = Matricula.objects.all().order_by('-id_matricula')[:1]
    nvalor = None
    codigo = ""
    for t in valor:
        nvalor = t.id_matricula + 1
    # verifico si el indice sigue vacio.
    if nvalor == None:
        nvalor = Matricula.objects.all().count() + 1
    if nvalor >= 10 and nvalor <= 99:
        codigo = "MAT-0" + str(nvalor)
    else:
        if nvalor > 99:
            codigo = "MAT-" + str(nvalor)
        else:
            codigo = "MAT-00" + str(nvalor)
    # codigo para Guardar matricula
    if request.method == 'POST':
        form = cMatriculaForm(request.POST)
        if form.is_valid():
            if form.save():
                # creacion del metodo para Generar un pago
                cdMatriccula = request.POST.get("cod_matricula")
                matriculacd = Matricula.objects.get(id_matricula=nvalor)
                dia = request.POST.get("fecha_matricula_day")
                mes = request.POST.get("fecha_matricula_month")
                anio = request.POST.get("fecha_matricula_year")
                fecha = anio + "-" + mes + "-" + dia
                date = datetime.datetime.strptime(fecha, "%Y-%m-%d").date()
                val = request.POST.get("valor_pagar")
                # proceso para generar el codigo del Pago
                idpago = None
                obpago = Pago.objects.all().order_by('-id')[:1]
                for i in obpago:
                    idpago = i.id + 1
                # verificamos idPago
                codigoP = " "
                if idpago == None:
                    idpago = Pago.objects.all().count() + 1
                if idpago >= 10 and idpago <= 99:
                    codigoP = "PAM-0" + str(idpago)
                else:
                    if idpago > 99:
                        codigoP = "PAM-" + str(idpago)
                    else:
                        codigoP = "PAM-00" + str(idpago)
                opago = Pago(cod_matricula=matriculacd, cod_pago=codigoP, descripcion='Matricula', obervaciones='NA',
                             fecha_generacion=date, valor_pagar=val, valor_pagado=0.0, estado=False)
                opago.save()
                msg = "Se Registro con exito Matricula " + request.POST.get("cod_matricula")
            return JsonResponse({'content': {'message': msg, 'color': 'success', }})
        else:
            msg = "Se genero un error al generar la Matricula " + request.POST.get(
                "cod_matricula") + "Al parecer esta matricula ya existe.!"
            return JsonResponse({'content': {'message': msg, 'color': 'danger', }})
    else:
        form = cMatriculaForm()
    contexto = {'form': form, 'admision': adm, 'Matriculas': materiasMatriculdas, 'ID': nvalor, 'codM': codigo,
                'valores': valores_pagar}
    return render(request, 'matriculas/FormMatriculacion.html', contexto)


class MatriculaFicha(UpdateView):
    model = Matricula
    form_class = cMatriculaForm
    template_name = 'matriculas/FichaMatricula.html'
    success_url = reverse_lazy('matricula:MatriculasList')

    def get_context_data(self, **kwargs):
        idM = self.kwargs.get('pk', None)
        mate = Matricula.objects.get(cod_matricula=idM)
        admision = admisione.objects.get(id=mate.admision_id.id)
        context = super(MatriculaFicha, self).get_context_data(**kwargs)
        context['Titulo'] = "Ficha Matricula"
        context['admision'] = admision
        context['matricula'] = mate
        return context


class pdfMatricula_view(LoginRequiredMixin, View):
    def link_callback(self, uri, rel):
        result = finders.find(uri)
        if result:
            if not isinstance(result, (list, tuple)):
                result = [result]
            result = list(os.path.realpath(path) for path in result)
            path = result[0]
        else:
            sUrl = settings.STATIC_URL  # Typically /static/
            sRoot = settings.STATIC_ROOT  # Typically /home/userX/project_static/
            mUrl = settings.MEDIA_URL  # Typically /media/
            mRoot = settings.MEDIA_ROOT  # Typically /home/userX/project_static/media/

            if uri.startswith(mUrl):
                path = os.path.join(mRoot, uri.replace(mUrl, ""))
            elif uri.startswith(sUrl):
                path = os.path.join(sRoot, uri.replace(sUrl, ""))
            else:
                return uri
        # make sure that file exists
        if not os.path.isfile(path):
            raise Exception(
                'media URI must start with %s or %s' % (sUrl, mUrl)
            )
        return path

    def get(self, request, *args, **kwargs):
        matricula = Matricula.objects.get(pk=self.kwargs['pk'])
        user = User.objects.get(
            username=self.request.user)  # envia el usuario que esta en la logueado en la aplicacion.
        template_path = 'matriculas/Reportes/Matricula.html'
        fecha = datetime.date.today()
        context = {'tittle': 'Reporte de Matricula :', 'matricula': matricula,
                   'codigo': matricula.admision_id.ci.ci,
                   'icon': '{}{}'.format(settings.MEDIA_URL, 'logo13.png'),
                   'date': fecha,
                   'usuario': user
                   }
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename=' + matricula.admision_id.ci.ci + ".pdf"
        template = get_template(template_path)
        html = template.render(context)
        if request.POST.get('show_html', ''):
            response['Content-Type'] = 'application/text'
            response['Content-Disposition'] = 'attachment; filename="ABC.txt"'
            response.write(html)
        else:
            pisaStatus = pisa.CreatePDF(
                html.encode("UTF-8"), dest=response, link_callback=self.link_callback)
            if pisaStatus.err:
                return HttpResponse('We had some errors with code %s <pre>%s</pre>' % (pisaStatus.err, html))
        return response


def cMatriculaEditar(request, id_mat):
    mat = Matricula.objects.get(id_matricula=id_mat)
    adm = admisione.objects.get(id=mat.admision_id.id)
    valores_pagar = Valor_matricula.objects.all().filter(cod_programa=adm.Programa.id).order_by('-id')[:1]
    materiasMatriculdas = Matricula.objects.all().filter(admision_id=adm.id)
    valor = Matricula.objects.all().order_by('-id_matricula')[:1]
    if request.method == 'POST':
        form = cMatriculaForm(request.POST, instance=mat)
        if form.is_valid():
            if form.save():
                msg = "Se Registro con exito la modificacion" + request.POST.get("cod_matricula")
            return JsonResponse({'content': {'message': msg, 'color': 'success', }})
        else:
            msg = "Se genero un error al EDITAR la Matricula " + request.POST.get(
                "cod_matricula") + ".!"
            return JsonResponse({'content': {'message': msg, 'color': 'danger', }})
    else:
        form = cMatriculaForm(instance=mat)
        #form = cMatriculaForm()
    contexto = {'form': form, 'admision': adm, 'Matriculas': materiasMatriculdas, 'ID': mat.id_matricula,
                'codM': mat.cod_matricula,
                'valores': valores_pagar}
    return render(request, 'matriculas/FormEditarMatricula.html', contexto)

sitefucidi/templates/matriculas/FormMatriculacion.html
 <div class="modal-dialog modal-lg"  id="ModalMatricula" role="document">
  <div class="modal-content">
      <div class="modal-header">
        {% block titlemodal %} <h5 class="modal-title" id="exampleModalLabel"> <b>Formulario de Matricula : {{codM}}</b> </h5>{% endblock %}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
          {% block modalcuerpo%}
        <form data-post-url="{% url 'matricula:Matricula' admision.id %}" id= "form_GenerarMatricula"  method="POST">
            {% csrf_token %}
          <div style="border-radius: 25px; border: 1px solid #05548C; margin: 1em 1em 0 1em; ">
           <div class="modal-body">
               <div class="row">
                 <div class="col-md-6 pr-1">
                    <div class="form-group">
                    <label>Codigo de Matricula: </label>
                    <input type="text" name="cod_matricula" class="form-control" maxlength="10" required="" value="{{codM}} " readonly id="id_cod_matricula">
                    <input type="hidden" name="id_matricula" class="form-control" required="" id="id_id_matricula" value="{{ID}}">
                    <input type="hidden" name="admision_id" class="form-control"  value="{{admision.id}}" required="" id="id_admision_id">
                    </div>
                 </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Modalidad: </label>
                        {{form.modalidad}}
                    </div>
                </div>
               </div>
               <div class="row">
                 <div class="col-md-6 pr-1">
                    <div class="form-group">
                    <label>Codigo de Admisión: </label>
                        <input type="text" class="form-control" name="1" readonly value="{{admision.codigoAdmision}}">
                    </div>
                 </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Programa de Estudio:</label>
                        <input type="text" class="form-control" name="2" readonly value="{{admision.Programa.nombre_programa}}">
                    </div>
                </div>
             </div>
               <div class="row">
                 <div class="col-md-6 pr-1">
                    <div class="form-group">
                    <label>Nombre del Estudiante: </label>
                        <input type="text" class="form-control" name="3"  readonly value="{{admision.ci.nombre}} {{admision.ci.apellido}}">
                    </div>
                 </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Valor de Matricula</label>
                        <select name="4" class="form-control"  readonly id="valores">
                        {% for val in valores %}
                               <option value="{{val.valor_matricula_presencial}}"> ${{val.valor_matricula_presencial}} (Presencial)</option>
                               <option value="{{val.valor_matricula_online}}"> ${{val.valor_matricula_online}}(Online)</option>
                        {%endfor%}
                        </select>
                    </div>
                </div>
               </div>
               <div class="row">
                 <div class="col-md-6 pr-1">
                    <div class="form-group">
                    <label>Fecha Matricula (dd/mm/aaaa): </label>
                        <br>
                        {{form.fecha_matricula}}
                    </div>
                 </div>
                <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Procentaje de beca: </label>
                        {{form.porcentaje_beca}}
                    </div>
                </div>
               </div>
                <div class="row">
                 <div class="col-md-6 pr-1">
                    <div class="form-group">
                    <label>Extension: </label>
                        {{form.extesion}}
                    </div>
                 </div>
                 <div class="col-md-6 pl-1">
                    <div class="form-group">
                        <label>Valor total a Pagar: </label>
                        {{form.valor_pagar}}
                    </div>
                 </div>
               </div>
           </div>
         <div class="modal-body">
             <b>Matriculas Anteriores: </b>
             <ol>
             {% for Matr in  Matriculas %}
                 <li> <span> <b>Codigo: </b>{{Matr.cod_matricula}} </span> </li>
             {% endfor %}
             </ol>
             <button class="btn btn-primary" type="submit">Matricular</button>
        </div>
   </div>
            <br><br>
   </form>
      {% endblock %}
    </div>
</div>

<script>
$(function() {
    'use strict';
    $('#id_modalidad').on('change', function() {
         var opcion = this.value;
         if(opcion=="Online")
         {
            alert("Has esocgido " + opcion);
            $("#valores").prop("selectedIndex", 1);
            var pagar = $("#valores").val();
            var bec =  $("#id_porcentaje_beca").val();
            var beca =  (parseFloat(bec) * parseFloat(pagar))/100;
            var valornuevo = parseFloat(pagar) - parseFloat(beca);
            $("#id_valor_pagar").val(valornuevo);
         }
         else
         {
            alert("Has esocgido " + opcion);
            $("#valores").prop("selectedIndex", 0);
            var pagar = $("#valores").val();
            var bec =  $("#id_porcentaje_beca").val();
            var beca =  (parseFloat(bec) * parseFloat(pagar))/100;
            var valornuevo = parseFloat(pagar) - parseFloat(beca);
            $("#id_valor_pagar").val(valornuevo);
         }
    });

    $('#id_porcentaje_beca').on('change', function() {
         var pagar = $("#valores").val();
         var bec =  $("#id_porcentaje_beca").val();
         var beca =  (parseFloat(bec) * parseFloat(pagar))/100;
         var valornuevo = parseFloat(pagar) - parseFloat(beca);
         $("#id_valor_pagar").val(valornuevo);
    });

    $('#form_GenerarMatricula').on('submit', function() {
       var post_url = $("#form_GenerarMatricula").data("post-url");
       var formData = new FormData(this);
        $.ajax({
            url : post_url,
            type: "POST",
            data : formData,
            processData: false,
            contentType: false,
            success:function(response){
                $("#id_materia_id").val(response.content.nuevo_id);
                var message = response.content.message
                demo.showNotification('bottom','right',message, response.content.color)
                $('#eliminar').modal('hide')
            },
        });
        return false;
    });




});
</script>

sitefucidi/templates/matriculas/generarMatricula.html
{% extends "matriculas/matriculas.html" %}

{% block title %}
FUCIDI-MATRICULAS
{% endblock %}

{%block cantidad%}
    <p class="card-category"></p>
    <a href="">
    <i class="fas fa-plus-square" style="font-size: 48px;"></i>
    </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Admisiones Activas</p>
    <p class="card-title">{{ActivosD}}<p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Admisiones Inactivas</p>
    <p class="card-title">{{InactivosD}}<p>
{% endblock %}


{% block il5 %} class="active" {% endblock %}
{%block titulofuncional %} <a><b> {{Titulo}} </b></a> {% endblock%}

{% block trabajo %}
<div class="table-responsive">
<table class="table table-hover table-bordered" id="datatable">
    <thead class="centrado-negrita">
    <tr>
        <td>N.</td>
        <td width="4">Código Admision</td>
        <td>Nombres y Apellidos</td>
        <td>Fecha Admision</td>
        <td>Programa de Estudio</td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody>
        {% if admisiones %}
        {% for adm in admisiones %}
        <tr>
            <td style="text-align:center;">{{forloop.counter}}</td>
            <td>{{ adm.codigoAdmision }}</td>
            <td>{{ adm.ci.nombre}} {{ adm.ci.apellido}}</td>
            <td>{{ adm.fecha }}</td>
            <td>{{ adm.Programa.nombre_programa }}</td>
            <td style="text-align:center;">
                <a class="btn btn btn-success" title="Generar Matricula" onclick="abrirmodaleliminar('{% url 'matricula:Matricula' adm.id %}'); " ><i class="fas fa-plus-square"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registos para mostrar</h1>
        {% endif %}
    </tbody>
</table>
</div>
{% endblock %}

sitefucidi/templates/matriculas/matriculas.html
{% extends "usuarios/base_panel.html" %}
{% block title %} Listado-Matriculas{% endblock %}

{%block cantidad%}
    <p class="card-category">Matriculas</p>
    <a href="{% url 'matricula:ListAdm'%}">Generar
    <i class="fas fa-plus-square"></i>
    </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Matriculas Vigentes</p>
    <p class="card-title"><p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Matriculas Pendientes</p>
    <p class="card-title"><p>
{% endblock %}

{% block path%} &nbsp; &nbsp; &nbsp; Módulo Matrícula  / Listado de Matrículas  {% endblock %}

{% block il5 %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->
    {%block titulofuncional %} <a><b> {{Titulo}} </b></a>
    <a href="{% url 'matricula:ListAdm'%}" class="btn btn-success btn-sm"><i class="fas fa-plus-square"></i>  Generar </a>
{% endblock%}

{% block trabajo %}
<div class="table-responsive">
<table class="table table-hover table-bordered" id="datatable">
    <thead  class="centrado-negrita">
    <tr>
        <td>N. Matricula</td>
        <td>Estudiante</td>
        <td>Programa de Estudio</td>
        <td>Fecha Matricula</td>
        <td>Extension</td>
        <td>Modalidad</td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody>
        {% if object_list %}
            {% for doc in object_list %}
                <tr>
                    <td style="text-align:center;">{{doc.cod_matricula}}</td>
                    <td>{{doc.admision_id.ci.nombre}} {{doc.admision_id.ci.apellido}}</td>
                    <td>{{doc.admision_id.Programa.nombre_programa}}</td>
                    <td>{{doc.fecha_matricula}}</td>
                    <td>{{doc.extesion}}</td>
                    <td style="text-align:center;">{{doc.modalidad}}</td>

                    <td style="text-align:center;">
                        <a CLASS="btn btn-primary" onclick="abrirmodaleliminar('{% url 'matricula:EditarMatricula' doc.id_matricula %}'); " title="Modificar" ><i class="fas fa-edit"></i> </a>
                        <a class="btn btn btn-success" title="Ficha Matricula" href="{% url 'matricula:MatriculaFicha' doc.cod_matricula %}"><i class="icon-big nc-icon nc-single-copy-04"></i></a>
                        <a class="btn btn-danger" onclick="" title="Eliminar" ><i class="fas fa-trash-alt"></i> </a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No hay registos para mostrar</h1>
        {% endif %}
    </tbody>
</table>
</div>
{% endblock %}