sitefucidi/Academico/urls.py
from django.urls import path
from .views import CprograLista, CprograNuevo, CprogramaEditar, CprogramaEliminar, CMateriaLista, CMateriaNuevo, \
    CMateriaEditar, CMateriaEliminar, EliminarPrograma, pdfMalla_view, pdfMateria_view, cAgregarValor, \
    CestudianteNotasView, CestudianteNotasMateriasView, CeditarNotaEstudiante, pdfNotasR_view, CModalReportes, \
    CModalReportesA, pdfAprobadoReprobado_view, CProgramaNuevoModal, CprogramaEditarModal

urlpatterns = [
    path('listar_programa/', CprograLista, name='Listar'),
    path('nuevo_programa/', CprograNuevo, name='Nuevo'),
    path('nuevo_programa1/', CProgramaNuevoModal, name='Nuevo1'), # Ejecuta la Modal con Respuesta JSON
    #path('editar/(?P<id_programa>\d+)/', CprogramaEditar, name='Editar'),
    path('editar/<int:id_programa>/', CprogramaEditar, name='Editar'),
    path('editar1/<int:id_programa>/', CprogramaEditarModal, name='Editar2'),
    #path('eliminar/(?P<id_programa>\d+)/', CprogramaEliminar, name='Eliminar'),
    path('eliminar/<int:id_programa>/', CprogramaEliminar, name='Eliminar'),
    #path('eliminar2/(?P<pk>\d+)/$', EliminarPrograma.as_view(), name='Eliminar2'),

    path('materias/', CMateriaLista, name='ListarMaterias'),
    # path('nueva_Materia/(?P<cd_programa>\d+)/', CMateriaNuevo, name='NuevaMateria'),
    path('nueva_Materia/<int:cd_programa>/', CMateriaNuevo, name='NuevaMateria'),
    path('editar_Materia/(?P<id_materia>\d+)/', CMateriaEditar, name='EditarMateria'),  # Editar Materia
    # path('eliminar_Materia/(?P<id_materia>\d+)/', CMateriaEliminar, name='EliminarMateria'),  # Eliminar Materia
    path('eliminar_Materia/<str:id_materia>/', CMateriaEliminar, name='EliminarMateria'),  # Eliminar Materia
    # path('programa/(?P<cd_programa>\d+)/$', cAgregarValor, name='Valores'),
    path('programa/(<int:cd_programa>/$', cAgregarValor, name='Valores'),

    path('notas/estudiantes/lista/', CestudianteNotasView, name="NotasListaEstudiante"),
    path('notas/estudiantes/lista/materias/(?P<id_est>\d+)/', CestudianteNotasMateriasView,
         name='NotasListaEstudianteMateria'),  # Materia Estudiante Notas
    path('notas/estudiantes/editar/nota/(?P<id_nota>\d+)/', CeditarNotaEstudiante, name='NotasEditar'),
    # path('notas/reporte/estudios/(?P<pk>\d+)/',pdfREporte_view.as_view(),name='ReporteEStudios'),
    path('notas/reporte/estudios/(?P<id_per>\d+)/', CModalReportes, name='ReporteEStudios'),

    # Reportes

    path('notas/reporte/certificado/estudios/(?P<pk>\d+)/(?P<cp>\d+)/', pdfNotasR_view.as_view(),
         name='ReporteEStudios1'),
    path('notas/reporte/aprobados/estudios/(?P<pk>\d+)/(?P<cp>\d+)/', pdfAprobadoReprobado_view.as_view(),
         name='AprobadoReporteEStudios'),

    path('generar/pdf', pdfMalla_view.as_view(), name='reporte_malla'),
    # path('generar_programa/pdf/(?P<pk>\d+)/', pdfMateria_view.as_view(), name='ReportePrograma'),  # Eliminar Materia
    path('generar_programa/pdf/<int:pk>/', pdfMateria_view.as_view(), name='ReportePrograma'),  # Eliminar Materia
    #path('generar/(?P<pk>\d+)/', CModalReportesA, name='xd'),
    path('generar/<int:pk>/', CModalReportesA, name='xd'),

    # path('generar/pdf', render_pdf, name='reporte_malla'),

]

sitefucidi/Admision/urls.py
from django.urls import path

from . import views
from .views import CAdmisionLista, AdmisionCreate, DocenteList, DocenteUpdate, CMateriasAsignadasDocente, \
    DocenteAgregar, DocenteEliminar, CMateriasAsignarRegitro, CMateriasAsignadasUpdate, EstudianteList, \
    EstudianteUpdate, EstudianteAgregar, EstudianteEliminar, CAdmisionListaEstudiante, cAdmisionNuevaEstudiante, \
    cAgregarDatosEstudiosRealizados, cAdmisionUpdateEstudiante, EstudianteSolicitud, FichaAdmisionPDF_view, \
    AdmisionElimnarView

urlpatterns = [

    path('admision/', CAdmisionLista, name='Listar'),
    path('nueva/', AdmisionCreate.as_view(), name='Nueva'),
    path('eliminar/<int:pk>', AdmisionElimnarView.as_view(), name="EliminarAdmision"), #introducir el parametro de ci para poder acceder a eliminar correctamente

    path('docentes/', DocenteList.as_view(), name='ListarDocente'),
    path('docentes/agregar/', DocenteAgregar.as_view(), name='NuevoDocente'),
    path('docentes/editar/(?P<pk>\d+)/$', DocenteUpdate.as_view(), name="EditarDocente"),
    path('docentes/eliminar/(?P<pk>\d+)/$', DocenteEliminar.as_view(), name="EliminarDocente"),

    path('docentes/Materias/(?P<id_docente>\d+)/$', CMateriasAsignadasDocente, name="ListaMateriasDocente"),
    path('docentes/Materias/Asignar/(?P<id_docente>\d+)/$', CMateriasAsignarRegitro, name="AsignarMateriasDocente"),
    path('docentes/Materias/Editar/(?P<pk>\d+)/$', CMateriasAsignadasUpdate, name="UpdateMateriasDocente"),

    path('estudiantes/(?P<slug>\d+)/$', EstudianteList.as_view(), name='ListarEstudiante'),
    path('estudiantes/agregar/', EstudianteAgregar.as_view(), name='NuevoEstudiante'),
    path('estudiantes/editar/(?P<pk>\d+)/$', EstudianteUpdate.as_view(), name="EditarEstudiante"),
    path('estudiantes/eliminar/(?P<pk>\d+)/$', EstudianteEliminar.as_view(), name="EliminarEstudiante"),

    path('estudiantes/admisiones/(?P<id_estu>\d+)/$', CAdmisionListaEstudiante, name="ListaAdmisionesEstudiante"),
    path('estudiantes/admisiones/nueva/(?P<id_estu>\d+)/$', cAdmisionNuevaEstudiante, name="NuevaAdmisionesEstudiante"),
    path('estudiantes/admisiones/editar/(?P<pk>\d+)/$', cAdmisionUpdateEstudiante, name="EditarAdmision"),

    # AREA COMUN PARA DATOS DE ADMISION INTRUCTORES Y ESTUDIANTES.
    path('estudiosRealizados/(?P<id_persona>\d+)/$', cAgregarDatosEstudiosRealizados, name="EstudiosRealizados"),

    # PARA QUE EL ESTUDIANTE PUEDA CREAR UNA SOLICITUD
    path('estudiantes/solicitud/', EstudianteSolicitud.as_view(), name='Solicitud'),

    # path('nuevo_programa/',CprograNuevo,name='Nuevo' ),
    # path('editar/(?P<id_programa>\d+)/',CprogramaEditar,name='Editar'),
    # path('eliminar/(?P<id_programa>\d+)/',CprogramaEliminar,name='Eliminar'),
    # path('materias/',CMateriaLista,name='ListarMaterias' ),
    # path('nueva_Materia/',CMateriaNuevo,name='NuevaMateria' ),
    # path('editar_Materia/(?P<id_materia>\d+)/',CMateriaEditar,name='EditarMateria'), #Editar Materia
    # path('eliminar_Materia/(?P<id_materia>\d+)/',CMateriaEliminar,name='EliminarMateria'), #Eliminar Materia

    # reporte
    path('admision/pdf/<int:pk>/', FichaAdmisionPDF_view.as_view(), name='ReporteFichaAdmision')

]

sitefucidi/Pago/urls.py
from django.urls import path

from .views import PagosMatriculaList, cAgregarValor, pdfPagoMatricula_view, PagosColegiaturaList, \
    PagosColegiaturaEstudHabilList, cAgregarPago, cFichaPago, pdfEstadoPagoMatricula_view, pdfEstadoPagoMatricula_view1, \
    pdfPagoColegiatura_view

urlpatterns = [
    path('lista/', PagosMatriculaList.as_view(), name='PagoLista'),
    path('detalle/pagos/(?P<id_pago>\d+)/$', cAgregarValor, name='PagoDetalle'),

    path('pago/matricula/pdf/(?P<pk>\d+)/', pdfPagoMatricula_view.as_view(), name='ReportePagoMatricula'),

    path('reportes/(?P<pk>\d+)/', pdfEstadoPagoMatricula_view.as_view(), name='ReporteGeneralPago'),

    path('pago/matricula/pdf/reporte/pago1/', pdfEstadoPagoMatricula_view1.as_view(), name='ReporteGeneralPago1'),
    #creacion de urls para pagos de colegiatura

    path('lista_pc/', PagosColegiaturaList.as_view(), name='PagoListaColegiatura'),
    path('lista_est_pc/', PagosColegiaturaEstudHabilList.as_view(), name='PagoEstudianteHabColegiatura'),
    path('agregar/pago/(?P<id_pago>\d+)/$', cAgregarPago, name='PagoColegiatura'),
    path('ficha/pago/(?P<id_pago>\d+)/$', cFichaPago, name='FichaPagoColegiatura'),
    path('pago/colegiatura/pdf/(?P<pk>\d+)/', pdfPagoColegiatura_view.as_view(), name='ReportePagoColegiatura'),




]

sitefucidi/sitefucidi/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', admin.site.urls,name='login'),
    path('', LoginView.as_view(template_name='usuarios/index.html'), name="Menu"),
    path('salir/', LogoutView.as_view(template_name='usuarios/index.html'), name="logout"),
    path('Menu', include('administrador.urls')),
    path('profile/', include(('administrador.urls', 'prof'), namespace='prof'),name='prof'),
    path('academia/', include(('Academico.urls', 'academia'), namespace='academia'),name='academia'),
    path('admision/', include(('Admision.urls', 'admision'), namespace='admision'),name='admision'),# incluimos las urls de admision para generar el sistema
    path('matricula/', include(('Matricula.urls', 'matricula'), namespace='matricula'), name='matricula'), # incluimos las urls de admision para generar el sistema
    path('pagos/', include(('Pago.urls', 'pago'), namespace='pago'), name='pago'), # incluimos las urls de admision para generar el sistema

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitefucidi/Academico/models.py
from django.db import models


# Create your models here.

class Programa(models.Model):
    opciones = (
        ('N', 'No definido'),
        ('A', 'Anual'),
        ('M', 'Mensual'),
    )

    cod_programa = models.CharField(max_length=10, null=False, verbose_name="Codigo Prograna", unique=True)
    nombre_programa = models.CharField(max_length=70, null=False, verbose_name="Programa")
    duracion = models.IntegerField(verbose_name="Duracion")
    tipo_programa = models.CharField(max_length=10, default=None, choices=opciones, verbose_name="Modalidad Programa")
    # precio_matricula = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor Matricula",default=None)
    # precio_pension = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor Pension",default=None)
    vigencia = models.BooleanField()

    def __str__(self):
        return '{}'.format(self.nombre_programa)


class Valor_matricula(models.Model):
    fecha = models.DateField(
        verbose_name="Fecha Asignada")  # solo se Permite una Fecha unica para los valores no se puede repetir en la tabal
    valor_matricula_presencial = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Matricula ",
                                                     default=None)
    valor_matricula_online = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor Matricula",
                                                 default=None)
    cod_programa = models.ForeignKey('Programa', on_delete=models.CASCADE, verbose_name="Codigo Prograna")
    # 001 12/04/2021  25.00 15.00 PA  order_by (desc).top(1)
    # 002 15/04/2021  25.00 10.00 PA


class Materia(models.Model):
    opcionesM = (
        ('C', 'Creditos'),
        ('H', 'Horas'),
    )
    nivels = (
        (1, 'Uno'),
        (2, 'Dos'),
        (3, 'Tres'),
    )
    materia_id = models.IntegerField(null=False)
    cod_programa = models.ForeignKey('Programa', on_delete=models.CASCADE, verbose_name="Codigo Prograna")
    cod_materia = models.CharField(max_length=10, verbose_name="Codigo Asignatura", primary_key=True)
    nombre_materia = models.CharField(max_length=70, null=False, verbose_name="Asignatura")
    modalidad = models.CharField(max_length=10, choices=opcionesM)
    duracion = models.IntegerField(null=False)
    nivel = models.IntegerField(null=True, blank=True, choices=nivels, default=0)
    valor_presencial = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Presencial ")
    valor_online = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Online")
    estado = models.BooleanField()

    def __unicode__(self):
        return self.Programa.cod_programa

    def __str__(self):
        return '{}'.format(self.nombre_materia)


class CnotasEstudiante(models.Model):
    fecha_subir_nota = models.DateField(verbose_name="Fecha Nota")
    notaestudiante = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Nota")
    asitencia = models.IntegerField()
    id_pago_materia = models.ForeignKey('Pago.Pago', on_delete=models.CASCADE, verbose_name="Id_materia_recibir")
    # id del pago que se genero con esa orden de pago

sitefucidi/templates/academia/Eliminar.html
 <div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
      <div class="modal-header">
        {% block titlemodal %} <h5 class="modal-title" id="exampleModalLabel"> ELIMINAR </h5>{% endblock %}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
          {% block modalcuerpo%}
        <form action="{% url 'academia:Eliminar' programa.id %}" method="POST">
           <div class="modal-body">
             {% csrf_token %}
               <h3>¿Desea eliminar el Programa: <b>{{programa.nombre_programa}}?</b></h3>
                <button id="#eliminarP" class="btn btn-danger" type="submit">Eliminar</button>
                <a class="btn btn-default" href="{% url 'academia:Listar' %}">Cancelar</a>
           </div>
          </form>
          {% endblock %}
    </div>
</div>

sitefucidi/templates/academia/Valor_Matricula.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            {% block titlemodal %} <h5 class="modal-title" id="exampleModalLabel"><b>Agregar Valor Matricula</b></h5>{% endblock %}
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% block modalcuerpo%}

        <form action="{% url 'academia:Valores' programa  %}" method="POST">
            <div style="border-radius: 25px; border: 1px solid #05548C; margin: 1em 1em 0 1em; ">
                <div class="modal-body">
                    <b>Registrar valores a Pagar: </b>
                    <br>
                    <br>
                    {% csrf_token %}
                    <input type="hidden" name="cod_programa" class="form-control" required="" value="{{programa}}" id="id_cod_programa">
                    <div class="row">
                        <div class="col-md-6 pr-1">
                            <div class="form-group">
                                <label>Fecha:</label>
                                {{form.fecha}}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 pr-1">
                            <div class="form-group">
                                <label>Valor matricula Online:</label>
                                {{form.valor_matricula_online}}
                            </div>
                        </div>
                        <div class="col-md-6 pl-1">
                            <div class="form-group">
                               <label>Valor matricula Presencial:</label>
                                {{form.valor_matricula_presencial}}
                            </div>
                        </div>
                    </div>
                    <button id="#eliminarP" class="btn btn-primary" type="submit">Guardar</button>
                    <a class="btn btn-default" href="{% url 'academia:Listar' %}">Cancelar</a>
                </div>
            </div>
        </form>
        <div class="modal-body">
            <b>Historial de Precios: </b>
            <br>
            <br>
            <table class="table table-bordered">
                <thead style="color:Black; font-weight: bolder;">
                <tr>
                    <td>N°</td>
                    <td>Fecha</td>
                    <td>Valor Matricula Presencial</td>
                    <td>Valor Matricula Online</td>
                    <td>Acciones</td>
                </tr>
                </thead>
                <tbody>
                {% if Valores %}
                    {% for val in Valores %}
                    <tr>
                        <td>{{forloop.counter0}}</td>
                        <td>{{ val.fecha }}</td>
                        <td>{{ val.valor_matricula_presencial }}</td>
                        <td>{{ val.valor_matricula_online }}</td>
                        <td>
                            <a class="btn btn-danger" onclick="" title="Eliminar"><i class="fas fa-trash-alt"></i> </a>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <h1>No hay registos para mostrar</h1>
                {% endif %}
                </tbody>
            </table>
        </div>
        {% endblock %}
    </div>
</div>

sitefucidi/templates/academia/listar_programas.html
{% extends "usuarios/base_panel.html" %}
{% block title %} Academia-Programa{% endblock %}
{%block cantidad%}
    <p class="card-category">Programas</p>
    <a  class="btn btn-primary btn-sm" href="{% url 'academia:Nuevo' %}">Nuevo </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Programas Vigentes</p>
    <p class="card-title">{{pvigentes}}<p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Programas N. Vigentes</p>
    <p class="card-title">{{nvigentes}}<p>
{% endblock %}
{% block il6 %} class="active" {% endblock %}
{% block il %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->
{% block path%} &nbsp; &nbsp; &nbsp; Módulo Academia  / Gestión Programas Académicos {% endblock %}
{%block titulofuncional %} <b> Programas Académicos </b>  &nbsp; &nbsp; &nbsp;
<!--<a class="btn btn-success btn-sm" href="{% url 'academia:Nuevo' %}"><i class="fas fa-plus-square"> </i> Agregar </a> -->
<a class="btn btn-success btn-sm" href="#" onclick="abrirmodaleliminar('{% url 'academia:Nuevo1' %}'); "><i class="fas fa-plus-square"> </i> Agregar </a>
<a class="btn btn-info btn-sm" href="{% url 'academia:reporte_malla' %}"><i class="nc-icon nc-cloud-download-93"> </i> PDF Programas </a>
{% endblock%}

{% block trabajo %}
<div class="table-responsive">
<table class="table table-hover table-bordered" id="datatable">
    <thead class="centrado-negrita">
    <tr>
        <td>N°</td>
        <td>Codigo Programa</td>
        <td>Nombre Programa</td>
        <td>Duración</td>
        <td>Modalidad</td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody>
        {% if programas %}
        {% for program in programas %}
        <tr>
            <td style="text-align:center;">{{ forloop.counter }}</td>
            <td>{{ program.cod_programa }}</td>
            <td>{{ program.nombre_programa }}</td>
            <td style="text-align:center;">{{ program.duracion }}</td>
            {% if program.tipo_programa == 'A'%}
            <td>Anual/<strong>es</strong></td>
            {%else%}
               <td>Mensual/<strong>es</strong></td>
            {%endif%}

            <td style="text-align:center;">
                <!--<a CLASS="btn btn-primary" title="Editar"  href="{% url 'academia:Editar' program.id  %}" id=""><i class="fas fa-edit"></i> </a>-->
                <a CLASS="btn btn-primary" title="Editar"  href="#" onclick="abrirmodaleliminar('{% url 'academia:Editar2' program.id  %}'); " ><i class="fas fa-edit"></i> </a>
                <a CLASS="btn btn-info"  title="Valor Matricula"  onclick="abrirmodaleliminar('{% url 'academia:Valores' program.id  %}'); " ><i class="fas fa-plus-square"></i> </a>
                <a CLASS="btn btn-info"  title="Añadir Materias"  onclick="abrirmodaleliminar('{% url 'academia:NuevaMateria' program.id  %}'); " ><i class="nc-icon nc-single-copy-04"></i> </a>
                <a class="btn btn-success" title="Descargar" href="{% url 'academia:ReportePrograma' program.id  %}"><i class="nc-icon nc-cloud-download-93"></i></a>
                <a class="btn btn-danger" title="Eliminar" onclick="abrirmodaleliminar('{% url 'academia:Eliminar' program.id  %}'); "><i class="fas fa-trash-alt"></i> </a>
                <!--<button class="btn btn-danger" type="button" data-toggle="modal" onclick="abrirmodaleliminar('{% url 'academia:Eliminar' program.id  %}'); "> Eliminar</button> -->
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registos para mostrar</h1>
        {% endif %}
    </tbody>
</table>
</div>



{% endblock %}

sitefucidi/templates/academia/nuevo.html
{% extends "academia/listar_programas.html" %} <!-- accedo a esta plantilla por que asi se beria presentar la funcionalidad -->


{% block dir %}href="{% url 'academia:Listar' %}" {% endblock %}
{% block path%} &nbsp; &nbsp; &nbsp; Módulo Academia  / {{title}} Programa {% endblock %}
{%block titulofuncional %}   <a><b> {{title}} Programa Académico </b></a> {% endblock%}


{% block trabajo %}

<div>

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 pr-1">
                <div class="form-group">
                    <label>Codigo</label>
                    {{form.cod_programa}}
                </div>
            </div>
            <div class="col-md-6 pl-1">
                <div class="form-group">
                    <label>Nombre Programa</label>
                    {{form.nombre_programa}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 pr-1">
                <div class="form-group">
                    <label>Duracion Programa</label>
                    {{form.duracion}}
                </div>
            </div>
            <div class="col-md-6 pl-1">
                <div class="form-group">
                    <label>Escoja un tipo (Anual o Semestral)</label>
                    {{form.tipo_programa}}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 pr-1">
                <div class="form-group">
                    <label>Vigencia del Programa</label>
                    {{form.vigencia}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 pr-1">
                <div class="form-group">
                    <label>Nota:</label>
                    <p>Recuerde que debe agregar valor de matricula y colegiatura luego de registrar el programa de estudio
                    y asi mismo el conjunto de materias que se dictaran como parte del aprendizaje.</p>
                </div>
            </div>
        </div>
        <button type="submit" class=" btn btn-primary btn-round">{{title}}</button>
    </form>
</div>
{% endblock %}