sitefucidi/Admision/urls.py
from django.urls import path

from . import views
from .views import CAdmisionLista, AdmisionCreate, DocenteList, DocenteUpdate, CMateriasAsignadasDocente, \
    DocenteAgregar, DocenteEliminar, CMateriasAsignarRegitro, CMateriasAsignadasUpdate, EstudianteList, \
    EstudianteUpdate, EstudianteAgregar, EstudianteEliminar, CAdmisionListaEstudiante, cAdmisionNuevaEstudiante, \
    cAgregarDatosEstudiosRealizados, cAdmisionUpdateEstudiante, EstudianteSolicitud, FichaAdmisionPDF_view, \
    AdmisionElimnarView

urlpatterns = [

    path('admision/', CAdmisionLista, name='Listar'),
    path('nueva/', AdmisionCreate.as_view(), name='Nueva'),
    path('eliminar/<int:pk>', AdmisionElimnarView.as_view(), name="EliminarAdmision"), #introducir el parametro de ci para poder acceder a eliminar correctamente

    path('docentes/', DocenteList.as_view(), name='ListarDocente'),
    path('docentes/agregar/', DocenteAgregar.as_view(), name='NuevoDocente'),
    path('docentes/editar/(?P<pk>\d+)/$', DocenteUpdate.as_view(), name="EditarDocente"),
    path('docentes/eliminar/(?P<pk>\d+)/$', DocenteEliminar.as_view(), name="EliminarDocente"),

    path('docentes/Materias/(?P<id_docente>\d+)/$', CMateriasAsignadasDocente, name="ListaMateriasDocente"),
    path('docentes/Materias/Asignar/(?P<id_docente>\d+)/$', CMateriasAsignarRegitro, name="AsignarMateriasDocente"),
    path('docentes/Materias/Editar/(?P<pk>\d+)/$', CMateriasAsignadasUpdate, name="UpdateMateriasDocente"),

    path('estudiantes/(?P<slug>\d+)/$', EstudianteList.as_view(), name='ListarEstudiante'),
    path('estudiantes/agregar/', EstudianteAgregar.as_view(), name='NuevoEstudiante'),
    path('estudiantes/editar/(?P<pk>\d+)/$', EstudianteUpdate.as_view(), name="EditarEstudiante"),
    path('estudiantes/eliminar/(?P<pk>\d+)/$', EstudianteEliminar.as_view(), name="EliminarEstudiante"),

    path('estudiantes/admisiones/(?P<id_estu>\d+)/$', CAdmisionListaEstudiante, name="ListaAdmisionesEstudiante"),
    path('estudiantes/admisiones/nueva/(?P<id_estu>\d+)/$', cAdmisionNuevaEstudiante, name="NuevaAdmisionesEstudiante"),
    path('estudiantes/admisiones/editar/(?P<pk>\d+)/$', cAdmisionUpdateEstudiante, name="EditarAdmision"),

    # AREA COMUN PARA DATOS DE ADMISION INTRUCTORES Y ESTUDIANTES.
    path('estudiosRealizados/(?P<id_persona>\d+)/$', cAgregarDatosEstudiosRealizados, name="EstudiosRealizados"),

    # PARA QUE EL ESTUDIANTE PUEDA CREAR UNA SOLICITUD
    path('estudiantes/solicitud/', EstudianteSolicitud.as_view(), name='Solicitud'),

    # path('nuevo_programa/',CprograNuevo,name='Nuevo' ),
    # path('editar/(?P<id_programa>\d+)/',CprogramaEditar,name='Editar'),
    # path('eliminar/(?P<id_programa>\d+)/',CprogramaEliminar,name='Eliminar'),
    # path('materias/',CMateriaLista,name='ListarMaterias' ),
    # path('nueva_Materia/',CMateriaNuevo,name='NuevaMateria' ),
    # path('editar_Materia/(?P<id_materia>\d+)/',CMateriaEditar,name='EditarMateria'), #Editar Materia
    # path('eliminar_Materia/(?P<id_materia>\d+)/',CMateriaEliminar,name='EliminarMateria'), #Eliminar Materia

    # reporte
    path('admision/pdf/<int:pk>/', FichaAdmisionPDF_view.as_view(), name='ReporteFichaAdmision')

]

sitefucidi/Pago/urls.py
from django.urls import path

from .views import PagosMatriculaList, cAgregarValor, pdfPagoMatricula_view, PagosColegiaturaList, \
    PagosColegiaturaEstudHabilList, cAgregarPago, cFichaPago, pdfEstadoPagoMatricula_view, pdfEstadoPagoMatricula_view1, \
    pdfPagoColegiatura_view

urlpatterns = [
    path('lista/', PagosMatriculaList.as_view(), name='PagoLista'),
    path('detalle/pagos/(?P<id_pago>\d+)/$', cAgregarValor, name='PagoDetalle'),

    path('pago/matricula/pdf/(?P<pk>\d+)/', pdfPagoMatricula_view.as_view(), name='ReportePagoMatricula'),

    path('reportes/(?P<pk>\d+)/', pdfEstadoPagoMatricula_view.as_view(), name='ReporteGeneralPago'),

    path('pago/matricula/pdf/reporte/pago1/', pdfEstadoPagoMatricula_view1.as_view(), name='ReporteGeneralPago1'),
    #creacion de urls para pagos de colegiatura

    path('lista_pc/', PagosColegiaturaList.as_view(), name='PagoListaColegiatura'),
    path('lista_est_pc/', PagosColegiaturaEstudHabilList.as_view(), name='PagoEstudianteHabColegiatura'),
    path('agregar/pago/(?P<id_pago>\d+)/$', cAgregarPago, name='PagoColegiatura'),
    path('ficha/pago/(?P<id_pago>\d+)/$', cFichaPago, name='FichaPagoColegiatura'),
    path('pago/colegiatura/pdf/(?P<pk>\d+)/', pdfPagoColegiatura_view.as_view(), name='ReportePagoColegiatura'),




]

sitefucidi/sitefucidi/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', admin.site.urls,name='login'),
    path('', LoginView.as_view(template_name='usuarios/index.html'), name="Menu"),
    path('salir/', LogoutView.as_view(template_name='usuarios/index.html'), name="logout"),
    path('Menu', include('administrador.urls')),
    path('profile/', include(('administrador.urls', 'prof'), namespace='prof'),name='prof'),
    path('academia/', include(('Academico.urls', 'academia'), namespace='academia'),name='academia'),
    path('admision/', include(('Admision.urls', 'admision'), namespace='admision'),name='admision'),# incluimos las urls de admision para generar el sistema
    path('matricula/', include(('Matricula.urls', 'matricula'), namespace='matricula'), name='matricula'), # incluimos las urls de admision para generar el sistema
    path('pagos/', include(('Pago.urls', 'pago'), namespace='pago'), name='pago'), # incluimos las urls de admision para generar el sistema

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitefucidi/Pago/models.py
from django.db import models
from django.utils.html import escape

# Create your models here.



class Pago(models.Model):
    opciones = (
        ('Matricula', 'Matricula'),
        ('Colegiatura', 'Colegiatura'),
    )
    cod_matricula = models.ForeignKey('Matricula.Matricula',on_delete=models.CASCADE,verbose_name="Codigo Matricula" )
    cod_pago= models.CharField(max_length=10,verbose_name="Codigo Pago",null=False)
    descripcion = models.CharField(max_length=20,default=None,choices=opciones)
    obervaciones = models.CharField(max_length=100)
    fecha_generacion = models.DateField(verbose_name="Fecha Creado",default=None)
    valor_pagar = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor a Pagar",default=0.0)
    valor_pagado = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Valor a Pagar", default=0.0)
    estado = models.BooleanField(verbose_name="Estado")



class detalle_pagos(models.Model):
    fecha = models.DateField(verbose_name="Fecha Pago",default=None)
    valor_cancelado = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="Valor Cancelado", default=0.0)
    Valor_pendiente = models.DecimalField(max_digits=6, decimal_places=2,verbose_name="Valor Pendiente", default=0.0)
    evidencia = models.ImageField(upload_to="pagos/matricula",verbose_name="Respaldo",null=True,default=None)
    pago_id = models.ForeignKey('Pago', on_delete=models.CASCADE, verbose_name="id_pago")

class materia_recibir(models.Model):
    fecha = models.DateField(verbose_name="Fecha Pago",default=None)
    materia_asignada = models.ForeignKey('Academico.Materia',on_delete=models.CASCADE, verbose_name="id_Materia")
    pago_id = models.ForeignKey('Pago', on_delete=models.CASCADE, verbose_name="id_pago")

sitefucidi/templates/gestion_pagos/ModalAgregarPago.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            {% block titlemodal %} <h5 class="modal-title" id="exampleModalLabel"><b>Agregar Pagos Matricula :
            {{pgd.cod_matricula}}</b></h5>{% endblock %}
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% block modalcuerpo%}
        <form action="{% url 'pago:PagoDetalle' id  %}" enctype="multipart/form-data" method="POST">
            <div style="border-radius: 25px; border: 1px solid #05548C; margin: 1em 1em 0 1em; ">
                <div class="modal-body">
                    <b>Registrar pago: </b>
                    <br>
                    <span>Sr(ita). Usted debe realizar el pago de matricula por un valor de <b>${{pgd.valor_pagar|floatformat:2 }}</b>. </span>
                    <br>
                    <span>Usted debe :  $<a id="id_saldo" style="color: red;">{{saldo|floatformat:2 }}</a> de <b>${{pgd.valor_pagar|floatformat:2 }}</b> </span>
                    <br>
                    <span><b>Nota</b>: En caso de no disponer el valor antes mencionado puede realizar los pagos en abonos.</span>
                    <br>
                    {% csrf_token %}

                    <select name="pago_id" class="form-control" required id="id_pago_id" style="visibility:hidden;">
  <option value="{{id}}" selected>---------</option>

</select>
                    <div class="row">
                        <div class="col-md-6 pr-1">
                            <div class="form-group">
                                <label>Fecha:</label>
                                {{form.fecha}}
                            </div>
                        </div>
                        <div class="col-md-6 pl-1">
                            <div class="form-group">
                                <label>Comprobante:</label>
                                <div class="file-upload">
                                    <div class="image-upload-wrap btn btn-success">
                                        <input class="file-upload-input" type='file' onchange="readURL(this);"
                                               accept="image/*" name="evidencia" class="form-control" accept="image/*" required="" id="id_evidencia" />
                                        <div class="drag-text">
                                            <span>Subir Archivo</span>
                                        </div>
                                    </div>
                                    <div class="file-upload-content">
                                        <img class="file-upload-image" src="#" alt="your image"/>
                                        <div class="image-title-wrap">
                                            <button type="button" onclick="removeUpload()" class="remove-image btn btn-danger">
                                               <i class="fas fa-trash-alt"></i>
                                                </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 pr-1">
                            <div class="form-group">
                                <label>Valor a Cancelar:</label>
                                <input type="number" name="valor_cancelado" value="0.0" class="form-control" step="0.05"
                                       min="1" max="{{pgd.valor_pagar}}" required="" id="id_valor_cancelado">
                            </div>
                        </div>
                        <div class="col-md-6 pl-1">
                            <div class="form-group">
                                <label>Saldo Pendiente:</label>
                                {{form.Valor_pendiente}}
                            </div>
                        </div>
                    </div>
                    {% if not saldo <= 0 %}
                        <button id="#eliminarP" class="btn btn-primary" type="submit">Guardar</button>
                    {% endif %}
                        <a class="btn btn-default" href="{% url 'academia:Listar' %}">Cancelar</a>
                    <span id="error"  style="color: red;" hidden>Existe un error en el formulario porfavor revise</span>
                </div>
            </div>
        </form>
        <div class="modal-body">
            <b>Pagos Realizados: </b>
            <br>
            <br>
            <table class="table table-bordered">
                <thead style="color:Black; font-weight: bolder;">
                <tr>
                    <td>N°</td>
                    <td>Fecha de pago</td>
                    <td>Valor Pagado</td>
                    <td>Saldo Pendiente</td>
                    <td>Acciones</td>
                </tr>
                </thead>
                <tbody>
                {% if Valores %}
                {% for val in Valores %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{ val.fecha }}</td>
                    <td>{{ val.valor_cancelado }}</td>
                    <td>{{ val.Valor_pendiente }}</td>
                    <td>
                        <a class="btn btn-danger" onclick="" title="Eliminar"><i class="fas fa-trash-alt"></i> </a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <h1>No hay registos para mostrar</h1>
                {% endif %}
                </tbody>
            </table>
        </div>
        {% endblock %}
    </div>
</div>

<script>

 function readURL(input) {
  if (input.files && input.files[0]) {

    var reader = new FileReader();

    reader.onload = function(e) {
      $('.image-upload-wrap').hide();

      $('.file-upload-image').attr('src', e.target.result);
      $('.file-upload-content').show();

      $('.image-title').html(input.files[0].name);
    };

    reader.readAsDataURL(input.files[0]);

  } else {
    removeUpload();
  }
}

function removeUpload() {
  $('.file-upload-input').replaceWith($('.file-upload-input').clone());
  $('.file-upload-content').hide();
  $('.image-upload-wrap').show();
}
$('.image-upload-wrap').bind('dragover', function () {
    $('.image-upload-wrap').addClass('image-dropping');
  });
  $('.image-upload-wrap').bind('dragleave', function () {
    $('.image-upload-wrap').removeClass('image-dropping');
});



$('#id_valor_cancelado').on('change', function() {
        saldo = $("#id_saldo").text();
        if ($('#id_valor_cancelado').val() > parseFloat(saldo))
        {
            alert("El valor a cancelar no puede ser mayor al saldo adeudado");
            $('#id_valor_cancelado').val(0,00);
            $('#id_valor_cancelado').focus();
            $("#id_Valor_pendiente").val(0,00);
            $('#id_Valor_pendiente').attr("readonly","readonly");
            $('#error').removeAttr("hidden");
        }
        else
        {
            $("#id_Valor_pendiente").val(parseFloat(saldo)-$("#id_valor_cancelado").val());
            $('#id_Valor_pendiente').attr("readonly","readonly");
            $('#error').attr("hidden","hidden");
        }

});

</script>

sitefucidi/templates/gestion_pagos/pagos_matricula.html
{% extends "usuarios/base_panel.html" %}
{% block title %} Pagos-Matriculas{% endblock %}

{%block cantidad%}
    <p class="card-category">Matriculas</p>
    <i class="fas fa-plus-square"></i>
    </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Total de Pagos</p>
    <p class="card-title"><p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Valor de Pagos</p>
    <p class="card-title"><p>
{% endblock %}




{% block path%} &nbsp; &nbsp; &nbsp; Módulo Pagos  / Listado de Pagos Matricula  {% endblock %}

{% block il8 %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->
    {%block titulofuncional %} <a><b> {{Titulo}} </b></a>

     <div class="col-md-6 pr-1">
        <div class="form-group">
           <select name="tipoReporte" id="id_tipoReporte" class="form-control" style="width:40%; display: inline-block;">
               <option value="R1">1. Reporte estudiantes que <strong>SI</strong> han pagado</option>
               <option value="R2">2. Reporte estudiantes que <strong>NO</strong> han pagado</option>
           </select>
           <a class="btn btn-info btn-sm" id="id_link" href="{% url 'pago:ReporteGeneralPago' 'R1'  %}"><i class="nc-icon nc-cloud-download-93"> </i> Reporte </a>

       </div>
     </div>
    {% endblock%}
{% block trabajo %}
<div class="table-responsive">
<table class="table table-hover table-bordered" id="datatable">
    <thead  class="centrado-negrita">
    <tr>
        <td>N. Pago</td>
        <td>Codigo Pago</td>
        <td>Fecha Pago</td>
        <td>Programa Estudio</td>
        <td>Estudiante</td>
        <td>Valor a Pagar</td>
        <td>Estado</td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody>
        {% if matriculas %}
            {% for pag in matriculas %}
                <tr>
                    <td style="text-align:center;">{{forloop.counter}}</td>
                    <td style="text-align:center;">{{pag.cod_pago}}</td>
                    <td>{{pag.fecha_generacion}}</td>
                    <td>{{pag.cod_matricula.admision_id.Programa.nombre_programa}}</td>
                    <td>{{pag.cod_matricula.admision_id.ci.nombre}} {{pag.cod_matricula.admision_id.ci.apellido}} </td>
                    <td style="text-align:center;">{{pag.valor_pagar}}</td>
                    {% if pag.estado %}
                        <td style="text-align:center;"> <a class="btn btn-success btn-circle" > <i class="fa fa-check"></i> </a> </td>
                    {%else%}
                        <td style="text-align:center;"> <a class="btn btn-danger btn-circle" > <i class="fa fa-times"></i></a>  </td>
                    {%endif%}
                    <td style="text-align:center;">
                        <a CLASS="btn btn-primary"  title="Modificar" href=""><i class="fas fa-edit"></i> </a>
                        <a class="btn btn-warning"  title="pagos" onclick="abrirmodaleliminar('{% url 'pago:PagoDetalle' pag.id  %}'); " ><i class="fas fa-plus-square"></i> </a>
                        <a class="btn btn-info" title="Ver Reporte" href=""><i class="icon-big nc-icon nc-single-copy-04"></i></a>
                        <a class="btn btn-success" title="Descargar"href="{% url 'pago:ReportePagoMatricula' pag.id %}" ><i class="nc-icon nc-cloud-download-93"></i> </a>
                        <a class="btn btn-danger" title="Eliminar" ><i class="fas fa-trash-alt"></i> </a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No hay registos para mostrar</h1>
        {% endif %}
    </tbody>
</table>
</div>

{% endblock %}