sitefucidi/Admision/urls.py
from django.urls import path

from . import views
from .views import CAdmisionLista, AdmisionCreate, DocenteList, DocenteUpdate, CMateriasAsignadasDocente, \
    DocenteAgregar, DocenteEliminar, CMateriasAsignarRegitro, CMateriasAsignadasUpdate, EstudianteList, \
    EstudianteUpdate, EstudianteAgregar, EstudianteEliminar, CAdmisionListaEstudiante, cAdmisionNuevaEstudiante, \
    cAgregarDatosEstudiosRealizados, cAdmisionUpdateEstudiante, EstudianteSolicitud, FichaAdmisionPDF_view, \
    AdmisionElimnarView

urlpatterns = [

    path('admision/', CAdmisionLista, name='Listar'),
    path('nueva/', AdmisionCreate.as_view(), name='Nueva'),
    path('eliminar/<int:pk>', AdmisionElimnarView.as_view(), name="EliminarAdmision"), #introducir el parametro de ci para poder acceder a eliminar correctamente

    path('docentes/', DocenteList.as_view(), name='ListarDocente'),
    path('docentes/agregar/', DocenteAgregar.as_view(), name='NuevoDocente'),
    path('docentes/editar/(?P<pk>\d+)/$', DocenteUpdate.as_view(), name="EditarDocente"),
    path('docentes/eliminar/(?P<pk>\d+)/$', DocenteEliminar.as_view(), name="EliminarDocente"),

    path('docentes/Materias/(?P<id_docente>\d+)/$', CMateriasAsignadasDocente, name="ListaMateriasDocente"),
    path('docentes/Materias/Asignar/(?P<id_docente>\d+)/$', CMateriasAsignarRegitro, name="AsignarMateriasDocente"),
    path('docentes/Materias/Editar/(?P<pk>\d+)/$', CMateriasAsignadasUpdate, name="UpdateMateriasDocente"),

    path('estudiantes/(?P<slug>\d+)/$', EstudianteList.as_view(), name='ListarEstudiante'),
    path('estudiantes/agregar/', EstudianteAgregar.as_view(), name='NuevoEstudiante'),
    path('estudiantes/editar/(?P<pk>\d+)/$', EstudianteUpdate.as_view(), name="EditarEstudiante"),
    path('estudiantes/eliminar/(?P<pk>\d+)/$', EstudianteEliminar.as_view(), name="EliminarEstudiante"),

    path('estudiantes/admisiones/(?P<id_estu>\d+)/$', CAdmisionListaEstudiante, name="ListaAdmisionesEstudiante"),
    path('estudiantes/admisiones/nueva/(?P<id_estu>\d+)/$', cAdmisionNuevaEstudiante, name="NuevaAdmisionesEstudiante"),
    path('estudiantes/admisiones/editar/(?P<pk>\d+)/$', cAdmisionUpdateEstudiante, name="EditarAdmision"),

    # AREA COMUN PARA DATOS DE ADMISION INTRUCTORES Y ESTUDIANTES.
    path('estudiosRealizados/(?P<id_persona>\d+)/$', cAgregarDatosEstudiosRealizados, name="EstudiosRealizados"),

    # PARA QUE EL ESTUDIANTE PUEDA CREAR UNA SOLICITUD
    path('estudiantes/solicitud/', EstudianteSolicitud.as_view(), name='Solicitud'),

    # path('nuevo_programa/',CprograNuevo,name='Nuevo' ),
    # path('editar/(?P<id_programa>\d+)/',CprogramaEditar,name='Editar'),
    # path('eliminar/(?P<id_programa>\d+)/',CprogramaEliminar,name='Eliminar'),
    # path('materias/',CMateriaLista,name='ListarMaterias' ),
    # path('nueva_Materia/',CMateriaNuevo,name='NuevaMateria' ),
    # path('editar_Materia/(?P<id_materia>\d+)/',CMateriaEditar,name='EditarMateria'), #Editar Materia
    # path('eliminar_Materia/(?P<id_materia>\d+)/',CMateriaEliminar,name='EliminarMateria'), #Eliminar Materia

    # reporte
    path('admision/pdf/<int:pk>/', FichaAdmisionPDF_view.as_view(), name='ReporteFichaAdmision')

]

sitefucidi/Pago/urls.py
from django.urls import path

from .views import PagosMatriculaList, cAgregarValor, pdfPagoMatricula_view, PagosColegiaturaList, \
    PagosColegiaturaEstudHabilList, cAgregarPago, cFichaPago, pdfEstadoPagoMatricula_view, pdfEstadoPagoMatricula_view1, \
    pdfPagoColegiatura_view

urlpatterns = [
    path('lista/', PagosMatriculaList.as_view(), name='PagoLista'),
    path('detalle/pagos/(?P<id_pago>\d+)/$', cAgregarValor, name='PagoDetalle'),

    path('pago/matricula/pdf/(?P<pk>\d+)/', pdfPagoMatricula_view.as_view(), name='ReportePagoMatricula'),

    path('reportes/(?P<pk>\d+)/', pdfEstadoPagoMatricula_view.as_view(), name='ReporteGeneralPago'),

    path('pago/matricula/pdf/reporte/pago1/', pdfEstadoPagoMatricula_view1.as_view(), name='ReporteGeneralPago1'),
    #creacion de urls para pagos de colegiatura

    path('lista_pc/', PagosColegiaturaList.as_view(), name='PagoListaColegiatura'),
    path('lista_est_pc/', PagosColegiaturaEstudHabilList.as_view(), name='PagoEstudianteHabColegiatura'),
    path('agregar/pago/(?P<id_pago>\d+)/$', cAgregarPago, name='PagoColegiatura'),
    path('ficha/pago/(?P<id_pago>\d+)/$', cFichaPago, name='FichaPagoColegiatura'),
    path('pago/colegiatura/pdf/(?P<pk>\d+)/', pdfPagoColegiatura_view.as_view(), name='ReportePagoColegiatura'),




]

sitefucidi/sitefucidi/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrador/', admin.site.urls,name='login'),
    path('', LoginView.as_view(template_name='usuarios/index.html'), name="Menu"),
    path('salir/', LogoutView.as_view(template_name='usuarios/index.html'), name="logout"),
    path('Menu', include('administrador.urls')),
    path('profile/', include(('administrador.urls', 'prof'), namespace='prof'),name='prof'),
    path('academia/', include(('Academico.urls', 'academia'), namespace='academia'),name='academia'),
    path('admision/', include(('Admision.urls', 'admision'), namespace='admision'),name='admision'),# incluimos las urls de admision para generar el sistema
    path('matricula/', include(('Matricula.urls', 'matricula'), namespace='matricula'), name='matricula'), # incluimos las urls de admision para generar el sistema
    path('pagos/', include(('Pago.urls', 'pago'), namespace='pago'), name='pago'), # incluimos las urls de admision para generar el sistema

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitefucidi/Admision/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    opciones = (
        ('Instructor','Instructor'),
        ('Estudiante','Estudiante'),
        ('Administrativo', 'Administrativo'),
    )
    estado = (
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo'),
    )
    estado_civil = (
        ('Soltero(a)', 'Soltero(a)'),
        ('Casado(a)', 'Casado(a)'),
        ('Divorciado(a)', 'Divorciado(a)'),
        ('Viudo(a)', 'Viudo(a)'),
    )

    ci = models.CharField(max_length=10,primary_key=True,null=False,verbose_name="Documento Identidad")
    nombre = models.CharField(max_length=60,null = False)
    apellido = models.CharField(max_length=60,null = False)
    pais = models.CharField(max_length=20, verbose_name="Pais",null=True)
    provincia = models.CharField(max_length=20, verbose_name="Provincia",null=True)
    ciudad = models.CharField(max_length=20, verbose_name="Ciudad",null=True)
    direccion = models.CharField(max_length=50)
    tipo = models.CharField(max_length=15, default=None, choices=opciones, verbose_name="Tipo Persona")
    estado_c = models.CharField(max_length=15,default=None, choices=estado_civil,verbose_name="Estado Civil")
    fecha_nacimiento = models.DateField()
    edad = models.IntegerField(default=0,null=True)
    telefono = models.CharField(max_length=14,null = True)
    celular = models.CharField(max_length=14, null=True)
    correo = models.EmailField(default=None)
    cal_Emer = models.CharField(max_length=30, null=True, default="None")
    emer_tele = models.CharField(max_length=15,null=True, default="0900000000")
    estado = models.CharField(max_length=10, default=None, choices=estado, verbose_name="Estado")
    def __str__(self):
        return self.ci

# Requisitos que debe llevar una Solicitud de admision.
class Requisito(models.Model):
    codigo = models.CharField(max_length=10,null=False,verbose_name="Codigo Requisito")
    descripcion = models.CharField(max_length=100,null=False,verbose_name="Descripcion")

    def __str__(self):
        return '{}'.format(self.descripcion,)


#apartado de Experiencia Espiritual
class Experencia_espiritual(models.Model):
    fecha_conversion = models.DateField(verbose_name="Fecha de Conversion") #fecha de conversion de la persona
    fecha_bautismo = models.DateField(verbose_name="Fecha Bautismo Agua")  # fecha de bautismo de la persona
    bautismo_espiritual = models.BooleanField(verbose_name="Bautismo Espiritual")  # ¿has recibido Bautismo del espitiru Santo? si/no
    fecha_bautismo_es = models.DateField(verbose_name="Bautismo Espiritual", null=True) # Fecha Bautismo Esperitual
    obra_señor = models.BooleanField(verbose_name="Llamamiento Obra Señor") #¿Tienes llamamiento a la obra del señor? si/no
    desc_obra = models.CharField(verbose_name="Obra Señor",max_length=100,null=True) #Descripcion a la obra del señor
    doctrinas = models.BooleanField(verbose_name="Doctrinas de Iglesia") # Conoce doctrinas de la iglesia del Dios.
    opinion = models.CharField(verbose_name="Necesidad Principal",max_length=100,null=True) # Necesidades Pincipales de la iglesia de hoy ?
    contribucion = models.CharField(verbose_name="Contribucion", max_length=100,null=True)  # Contribucion Necesidades Pincipales de la iglesia de hoy ?
    motivacion = models.CharField(verbose_name="Motivacion", max_length=100,null=True)  # Motivacion Ingresar a Seminarios.

# apartado de Trasfondo eclesiastico
class Trasfondo_eclesiastico(models.Model):
    iglesia= models.CharField(verbose_name="Iglesia Perteneciente", null=True, max_length=100) # ¿A que iglesia Pertenece?
    denominacion = models.CharField(verbose_name="Denominacion", null=True, max_length=100) # Denominacion
    direcion = models.CharField(verbose_name="Direccion Iglesia", null=True, max_length=200) # Direccion Iglesia, en el formulario considerar Calle, Canton, Provincia
    miembro = models.BooleanField(verbose_name="Miembro") # ¿Eres mienbro?
    fecha_menbresia = models.DateField(verbose_name="Fecha Menbresia",null=True)
    cargo_desempeñado = models.CharField(verbose_name="Cargos Desempeñados",null=True, max_length=200)
    nom_apellido = models.CharField(verbose_name="Nombre y Apellido Pastor", null=True, max_length=70)

#aparatado de estudos realizados
class estudios_realizado(models.Model):
    opciones = (
        ('Primarios', 'Primarios'),
        ('Secundarios', 'Secundarios'),
        ('Universitarios', 'Universitarios'),
        ('Religiosos', 'Religiosos'),
        ('Otros', 'Otros'),
    )

    tipo_est=models.CharField(verbose_name="Tipo Estutdios", choices=opciones,max_length=20,null=True)
    fecha_ini = models.DateField(verbose_name="Fecha Inicio",null=True)
    fecha_fin = models.DateField(verbose_name ="Fecha Final",null=True)
    institucion = models.CharField(verbose_name="Nombre Institucion",null=True, max_length=100)
    graduacion = models.BooleanField(verbose_name="Graduacion")
    ci = models.ForeignKey('Persona', on_delete=models.CASCADE, verbose_name="Estudio de")

# aparatado de Recomendaciones
class recomendaciones(models.Model):
    nombre_apellido = models.CharField(verbose_name="Nombre y Apellidos",null=True,max_length=70)
    direccion = models.CharField(verbose_name="Direccion Domicilio", null=True, max_length=100)
    telefono = models.CharField(verbose_name="telefono", null=True,max_length=11)
    ci = models.ForeignKey('Persona', on_delete=models.CASCADE, verbose_name="Referencia de")

class admisione(models.Model):
    codigoAdmision = models.CharField(verbose_name="Codigo de Admision", null=False,max_length=10)
    ci = models.ForeignKey('Persona', on_delete=models.CASCADE, verbose_name="Cedula Admision")
    id_ex = models.ForeignKey('Experencia_espiritual', on_delete=models.CASCADE, verbose_name="Id  Experiencia")
    id_tra = models.ForeignKey('Trasfondo_eclesiastico',on_delete=models.CASCADE, verbose_name="Id Transfondo")
    id_requisito = models.ManyToManyField('Requisito')
    id_estudios = models.ManyToManyField('estudios_realizado')
    id_refecencia = models.ManyToManyField('recomendaciones')
    Programa = models.ForeignKey('Academico.Programa',blank=True,null=False,default=1,on_delete=models.CASCADE,verbose_name="Programa Estudiar")
    fecha = models.DateField(verbose_name="Fecha Solicitud",null=True)
    foto = models.ImageField(upload_to='admision_images',null=True,blank=True)

    def __str__(self):
        return self.codigoAdmision

class asignacionMaterias(models.Model):

    instructor = models.ForeignKey('Persona', on_delete=models.CASCADE, verbose_name="Cedula Instructor")
    fecha_Asignacion = models.DateField(verbose_name="Fecha Asignacion",null=True, blank=True)
    materias = models.ManyToManyField('Academico.Materia')
    estado_asig = models.BooleanField()

#class admisione_requisito(models.Model):
#    id = models.AutoField()
#    id_admision = models.ForeignKey('admisione',primary_key=True,on_delete=models.CASCADE)
#    id_requisto = models.ForeignKey('Requisito',primary_key=True,on_delete=models.CASCADE)

#class  admisione_estudio(models.Model):
#    id = models.AutoField()
#    id_admision = models.ForeignKey('admisione',primary_key=True,on_delete=models.CASCADE)
#    id_estudios = models.ForeignKey('estudios_realizado',primary_key=True,on_delete=models.CASCADE)

#class admisione_referencia(models.Model):
#    id = models.AutoField()
#    id_admision = models.ForeignKey('admisione', primary_key=True,on_delete=models.CASCADE)
#    id_refecencia = models.ForeignKey('recomendaciones', primary_key=True,on_delete=models.CASCADE)

sitefucidi/templates/admision/Instructor/Asignar_materias.html
{% extends "admision/Instructor/instructor.html" %}
{%block cantidad%}
    <p class="card-category">Asignar</p>
    <a href="{% url 'admision:AsignarMateriasDocente' doc.ci %}">
    <i class="fas fa-plus-square" style="font-size: 48px;"></i>
    </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Asignaciones Activas</p>
    <p class="card-title">{{ActivosD}}<p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Asignacion Inactiva</p>
    <p class="card-title">{{InactivosD}}<p>
{% endblock %}


{% block dir %} href="{% url 'admision:ListaMateriasDocente' doc.ci %}"{% endblock %}
{% block path%} &nbsp; &nbsp; &nbsp; Módulo Admisión  / Gestión Instructores / {{Titulo}}  {% endblock %}

{% block il7 %} class="active" {% endblock %}
{% block il3 %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->
{%block titulofuncional %} <a><b> {{Titulo}}: </b>   {{doc.nombre}} {{doc.apellido}} </a> {% endblock%}

{% block trabajo %}
<form method="post">
	{% csrf_token %}
    <input type="hidden" name="instructor" class="" value="{{doc.ci}}" id="id_instructor">
    <div class="row">
                     <div class="col-md-6 pr-1">
                      <div class="form-group">
                        <label>Fecha: </label>
                          {{form.fecha_Asignacion}}
                      </div>
                    </div>
                    <div class="col-md-6 pl-1">
                      <div class="form-group">
                        <label>Estado:</label>
                          {{form.estado_asig}}
                      </div>
                    </div>
    </div>
    <div class="row">
        <div class="col-md-6 pr-1">
             <div class="form-group">
                 <label>Seleccione Materias:</label>
                 <br> </br>
                 {{form.materias}}
             </div>
        </div>
    </div>
    <button type="submit" CLASS=" btn btn-primary btn-round">{{Titulo}}</button>
</form>
{% endblock %}

sitefucidi/templates/admision/Instructor/EditarDocente.html
{% extends "admision/Instructor/instructor.html" %}
{%block titulofuncional %} <a><b> {{Titulo}} Instructor</b></a> {% endblock%}
{% block path%} &nbsp; &nbsp; &nbsp; Módulo Admisión  / {{Titulo}} Instructor  {% endblock %}
{% block dir %} href="{% url 'admision:ListarDocente' %}"{% endblock %}

{% block trabajo %}
<div>

    <form method="post">
        {% csrf_token %}
             <div class="row">
                    <div class="col-md-6 pr-1">
                      <div class="form-group">
                        <label>Cedula/Pasaporte</label>
                          <input type="text" name="ci" value="{{form.ci.value}}" class="form-control" disabled="True" maxlength="10"  id="id_ci">
                          <input type="hidden" name="ci" value="{{form.ci.value}}" class="form-control" maxlength="10"  id="id_ci">
                      </div>
                    </div>
                    <div class="col-md-6 pl-1">
                      <div class="form-group">
                        <label>Estado</label>
                          {{form.estado}}
                      </div>
                    </div>
             </div>
             <div class="row">
                     <div class="col-md-6 pr-1">
                      <div class="form-group">
                        <label>Nombres</label>
                          {{form.nombre}}
                      </div>
                    </div>
                    <div class="col-md-6 pl-1">
                      <div class="form-group">
                        <label>Apellidos</label>
                          {{form.apellido}}
                      </div>
                    </div>
             </div>
             <div class="row">
                    <div class="col-md-5 pr-1">
                      <div class="form-group">
                        <label>Pais</label>
                        {{form.pais}}
                      </div>
                    </div>
                    <div class="col-md-3 px-1">
                      <div class="form-group">
                        <label>Provincia</label>
                         {{form.provincia}}
                      </div>
                    </div>
                    <div class="col-md-4 pl-1">
                      <div class="form-group">
                        <label>Ciudad</label>
                        {{form.ciudad}}
                      </div>
                    </div>
            </div>
             <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>Direccion</label>
                        {{form.direccion}}
                      </div>
                    </div>
             </div>
             <div class="row">
                    <div class="col-md-5 pr-1">
                      <div class="form-group">
                        <label>Tipo de Admision</label>
                        {{form.tipo}}
                          <input type="hidden" name="tipo" value="{{form.tipo.value}}" class="form-control" required="True" id="id_tipo">
                      </div>
                    </div>
                    <div class="col-md-3 px-1">
                      <div class="form-group">
                        <label>Estado Civil</label>
                         {{form.estado_c}}
                      </div>
                    </div>
                    <div class="col-md-4 pl-1">
                      <div class="form-group">
                        <label>Fecha de Nacimiento</label>
                        {{form.fecha_nacimiento}}
                      </div>
                    </div>
            </div>
             <div class="row">
                    <div class="col-md-5 pr-1">
                      <div class="form-group">
                        <label>Edad</label>
                        {{form.edad}}
                      </div>
                    </div>
                    <div class="col-md-3 px-1">
                      <div class="form-group">
                        <label>Telefono</label>
                         {{form.telefono}}
                      </div>
                    </div>
                    <div class="col-md-4 pl-1">
                      <div class="form-group">
                        <label>Celular</label>
                        {{form.celular}}
                      </div>
                    </div>
            </div>
             <div class="row">
                <div class="col-md-12">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Correo Electronico</label>
                        {{form.correo}}
                      </div>
                </div>
            </div>
             <a> <b>En caso de Emergencia comunicarse con: </b></a>
             <div class="row">
                     <div class="col-md-6 pr-1">
                      <div class="form-group">
                        <label>Nombres y Apellidos </label>
                          {{form.cal_Emer}}
                      </div>
                    </div>
                    <div class="col-md-6 pl-1">
                      <div class="form-group">
                        <label>Telefono</label>
                          {{form.emer_tele}}
                      </div>
                    </div>
             </div>
        <button type="submit" CLASS=" btn btn-primary btn-round">{{Titulo}}</button>
    </form>
</div>
{% endblock %}

sitefucidi/templates/admision/Instructor/Listado_materias_asignadas.html
{% extends "usuarios/base_panel.html" %}
{%block cantidad%}
    <p class="card-category">Asignar</p>
    <a href="{% url 'admision:AsignarMateriasDocente' Docente.ci %}">
    <i class="fas fa-plus-square" style="font-size: 48px;"></i>
    </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Asignaciones Activas</p>
    <p class="card-title">{{ActivosD}}<p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Asignacion Inactiva</p>
    <p class="card-title">{{InactivosD}}<p>
{% endblock %}

{% block dir %} href="{% url 'admision:ListarDocente' %}"{% endblock %}
{% block path%} &nbsp; &nbsp; &nbsp; Módulo Admisión  / Gestión Instructores / Asignacion Materias  {% endblock %}
{% block il7 %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->

{% block il3 %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->

    {%block titulofuncional %} <a><b> {{TituloFuncionalidad}}: </b>   {{Docente.nombre}} {{Docente.apellido}} </a>
    &nbsp; &nbsp; &nbsp;
    <a class="btn btn-success btn-sm" href="{% url 'admision:AsignarMateriasDocente' Docente.ci %}"><i class="fas fa-plus-square"> </i> Agregar </a>
    {% endblock%}

{% block trabajo %}
<div class="table-responsive">

<table class="table table-hover table-bordered" id="datatable">
    <thead class="centrado-negrita">
    <tr>
        <td>Materia(s) </td>
        <td>Fecha de Asignacion</td>
        <td>Estado </td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody>
        {% if materiasAsig %}
        {% for mta in materiasAsig %}
        <tr>
            <td>
                <ul style="list-style-type: decimal;">

                     {% for materia in mta.materias.all %}
                         <li>{{ materia.nombre_materia }} <b>|</b> <b style="color:red">({{ materia.cod_programa.cod_programa }}</b>)</li>
                     {% endfor %}
                </ul>
            </td>

            <td  style="text-align: center;">{{ mta.fecha_Asignacion }}</td>
            <td>{{ mta.estado_asig }}</td>
            <td style="text-align: center;">
                <a CLASS="btn btn-primary"  title="Modificar" href="{% url 'admision:UpdateMateriasDocente' mta.id %}"><i class="fas fa-edit"></i> </a>
                <a class="btn btn btn-success" title="#" href=""><i class="icon-big nc-icon nc-single-copy-04"></i></a>
                <a class="btn btn-danger" onclick="" title="Eliminar" ><i class="fas fa-trash-alt"></i> </a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registos para mostrar</h1>
        {% endif %}
    </tbody>
</table>
    </div>
{% endblock %}

sitefucidi/templates/admision/Instructor/eliminar.html
 <div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
      <div class="modal-header">
        {% block titlemodal %} <h5 class="modal-title" id="exampleModalLabel"> ELIMINAR </h5>{% endblock %}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
          {% block modalcuerpo%}
        <form action="{% url 'admision:EliminarDocente' persona.ci %}" method="POST">
           <div class="modal-body">
             {% csrf_token %}
               <h3>¿Desea eliminar al instructor: <b>{{ persona.nombre }} {{ persona.apellido }}?</b></h3>
                <button id="#eliminarP" class="btn btn-danger" type="submit">Eliminar</button>
                <a class="btn btn-default" href="{% url 'admision:ListarDocente' %}">Cancelar</a>
           </div>
          </form>
          {% endblock %}
    </div>
</div>

sitefucidi/templates/admision/Instructor/instructor.html
{% extends "usuarios/base_panel.html" %}
{% block title %} Admision-Instructor{% endblock %}
{%block cantidad%}
    <p class="card-category">Docentes</p>
    <a href="{% url 'admision:NuevoDocente'%}">
    <i class="fas fa-plus-square" style="font-size: 48px;"></i>
    </a>
{% endblock %}
{% block opcion2 %}
    <p class="card-category">Docentes Activos</p>
    <p class="card-title">{{ActivosD}}<p>
{% endblock %}

{% block opcion3 %}
    <p class="card-category">Docentes Inactivos</p>
    <p class="card-title">{{InactivosD}}<p>
{% endblock %}

{% block path%} &nbsp; &nbsp; &nbsp; Módulo Admision  / Gestión Instructores {% endblock %}
{% block il3 %} class="active" {% endblock %} <!-- clase para saber en que menuestas -->
{% block il7 %} class="active" {% endblock %}
{%block titulofuncional %} <a><b> Instructores </b></a>   &nbsp; &nbsp; &nbsp;
    <a class="btn btn-success btn-sm" href="{% url 'admision:NuevoDocente'%}"><i class="fas fa-plus-square"> </i> Agregar </a>
{% endblock%}
{% block trabajo %}
<div class="table-responsive">

<table  class="table table-hover table-bordered" id="datatable">
    <thead class="centrado-negrita">
    <tr>
        <td>Identificacion</td>
        <td>Nombres</td>
        <td>Apellidos</td>
        <td>Provincia</td>
        <td>Ciudad</td>
        <td>Direcion</td>
        <td>Celular</td>
        <td>Correo Electronico</td>
        <td>Estado</td>
        <td>Acciones</td>
    </tr>
    </thead>

    <tbody>
        {% if object_list %}
        {% for doc in object_list %}
        <tr>
            <td style="text-align:center;">{{ doc.ci }}</td>
            <td>{{ doc.nombre }}</td>
            <td>{{ doc.apellido }}</td>
            <td>{{ doc.provincia }}</td>
            <td>{{ doc.ciudad }}</td>
            <td>{{ doc.direccion }}</td>
            <td>{{ doc.celular }}</td>
            <td>{{ doc.correo }} </td>
            <td>{{ doc.estado }}</td>
            <td  style="text-align: center;" >
                <!--admision:ListarDocente-->
                <a CLASS="btn btn-primary"  title="Modificar" href="{% url 'admision:EditarDocente' doc.ci %}"><i class="fas fa-edit"></i> </a>
                <!--<a CLASS="" href="{% url 'admision:EditarDocente' doc.ci %}"><i class="fas fa-edit"></i> </a>-->
                <a class="btn btn btn-success" title="Asignar Materias" href="{% url 'admision:ListaMateriasDocente' doc.ci %}"><i class="icon-big nc-icon nc-single-copy-04"></i></a>
                <a class="btn btn-danger" onclick="abrirmodaleliminar('{% url 'admision:EliminarDocente' doc.ci %}'); " title="Eliminar" ><i class="fas fa-trash-alt"></i> </a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registos para mostrar</h1>
        {% endif %}
    </tbody>
</table>
    </div>
{% endblock %}